services:
  redis:
    image: redis:latest
    container_name: redis_service
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

  nestjs:
    build: ./
    container_name: nestjs_service
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3000:3000'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
